In [24]:
import torch

# 텐서 만들기

x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("x =", x)
print("y =", y)
print(type(x), type(y))

x = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
y = tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
<class 'torch.Tensor'> <class 'torch.Tensor'>


In [25]:
# 크기와 랭크(차원) 확인하기

print(x.shape)
print(x.size()) # shape와 동일한 기능을 수행

print(x.ndim)   # Tensor가 몇 차원인지 알고 싶을 때
print(x.ndimension())   # 위와 동일
print(len(x.shape))     # 위와 동일

torch.Size([3, 3])
torch.Size([3, 3])
2
2
2


In [26]:
# 텐서 모양 바꾸기

# unsqueeze(x, i): 텐서 x에 i번째 차원 추가 
# vector -> matrix / matrix -> 3차원 tensor 가능

print(x)
print(x.shape)

x0 = torch.unsqueeze(x, 0)
x1 = torch.unsqueeze(x, 1)
x2 = torch.unsqueeze(x, 2)

print(x0)
print(x1)
print(x2)

print(x0.shape)
print(x1.shape)
print(x2.shape)

# squeeze(x): 텐서 x에서 크기가 1인 차원 제거 
print(torch.squeeze(x1))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
torch.Size([1, 3, 3])
torch.Size([3, 1, 3])
torch.Size([3, 3, 1])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [27]:
# x.view([shape]): x를 [shape]의 모양으로 변환
# shape을 정의하는 것에 따라 squeeze와 unsqueeze 기능을 모두 사용 가능

print(x)
print(x.view(9))

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [36]:
# 행렬 연산

x = torch.tensor([[1, 2], [3, 4], [5, 6]], dtype = torch.float)

w = torch.randn(2, 1, dtype = torch.float)
b = torch.randn(1, dtype = torch.float)

h = torch.mm(x, w) + b

print(w)

tensor([[ 0.6395],
        [-1.0623]])


In [37]:
# Autograd: 기울기 계산

w = torch.tensor(1.0, requires_grad = True)
a = w * 3
l = a ** 2
l.backward()

print('l을 w로 미분한 값은', w.grad)

l을 w로 미분한 값은 tensor(18.)


In [ ]:
# Linear Regression

x_train = torch.FloatTensor([[1, 2], [3, 2], [3, 7], [1, 1], [1, 0]])
y_train = torch.tensor([[4], [8], [23], [1], [-2]])

W = torch.randn(2, 1)
b = torch.randn(1)

lr = 0.01

for epoch in range(1000):
    w.requires_grad_(True)
    b.requires_grad_(True)

    h = torch.mm(x_train, w) + b
    cost = torch.mean((h - y_train) ** 2)

    cost.backward()
    
    with torch.no_grad(): # 기울기 계산을 하지 않고 결과만을 사용함
        w = w - lr * w.grad
        b = b - lr * b.grad

In [38]:
# sklearn을 이용한 Linear Regression

from sklearn.linear_model import LinearRegression

x = [[1, 2], [3, 2], [3, 7], [1, 1], [1, 0]]
y = [[4], [8], [23], [1], [-2]]

model = LinearRegression()
model.fit(x, y)

model.coef_ # w
model.intercept_ # b

x_test = [[5, 10]]
y_test = model.predict(x_test)
print(y_test)


[[36.]]
